import Head from 'next/head'
import Hero from '../components/Hero'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Blockchain App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>

      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1> 

    </div>
  )
}
